export const SalesHistoryPayload = {
  update: {
    member: "",
    route: "",
    phone: "",
    nrc: "",
    seat: "",
    total: "",
    note: "",
    startTime: "",
    status: "",
    id: "",
    role: "",
  },
  store: {
    member: "",
    route: "",
    phone: "",
    nrc: "",
    seat: "",
    total: "",
    note: "",
    startTime: "",
    status: "",
    id: "",
    role: "",
  },
  columnsName: "salesHistoryColumns",
  columns: [
    { id: "created_at", label: "Created At", minWidth: 100 },
    { id: "created_by", label: "Name", minWidth: 200 },
    { id: "start_time", label: "Start Time", minWidth: 200 },
    { id: "route_name", label: "Route", minWidth: 200 },
    { id: "name", label: "Name", minWidth: 200 },
    { id: "nrc", label: "Nrc", minWidth: 170 },
    { id: "phone", label: "Phone", minWidth: 100 },
    { id: "seat", label: "Seat", minWidth: 300 },
    { id: "total", label: "Total", minWidth: 100 },
    { id: "commission", label: "Commission", minWidth: 100 },
    { id: "note", label: "Note", minWidth: 200 },
    { id: "is_settled", label: "Is Settled", minWidth: 200 },
    // { id: "payment_name", label: "Payment", minWidth: 100 },
    // { id: "status", label: "Status", minWidth: 100 },
    // { id: "screenshot", label: "Screenshot", minWidth: 80 },

    // { id: "updated_by", label: "Updated By", minWidth: 100 },
    // { id: "updated_at", label: "Updated At", minWidth: 100 },

    // { id: "option", label: "Option", minWidth: 100 },
  ],
  paginateParams: {
    page: 1,
    per_page: 10,
    columns:
      "route_name,start_time,name,seat,payment_name,status,commission,created_by,option",
    search: "",
    order: "created_at",
    sort: "DESC",
    value: "",
    start_date: "",
    end_date: "",
  },
  agentPaginateParams: {
    page: 1,
    per_page: 10,
    columns:
      "route_name,start_time,name,seat,payment_name,status,commission,created_by,option",
    search: "",
    order: "created_at",
    sort: "DESC",
    value: "",
    start_date: "",
    end_date: "",
  },
};
