export const promotionPayload = {
  store: {
    title: "",
    discount_text: "",
    popup_image: "",
    popup_image_file: null,
    coupon_code: "",
    discount_percentage: 0,
    display_type: "both",
    show_on_checkout: false,
    start_date: "",
    end_date: "",
    is_active: true,
    show_on_web: false,
    show_on_mini_app: true,
    show_on_android: false,
    show_on_ios: false,
  },
  update: {
    title: "",
    discount_text: "",
    popup_image: "",
    popup_image_file: null,
    coupon_code: "",
    discount_percentage: 0,
    display_type: "both",
    show_on_checkout: false,
    start_date: "",
    end_date: "",
    is_active: true,
    show_on_web: false,
    show_on_mini_app: true,
    show_on_android: false,
    show_on_ios: false,
  },
};

