export const agentPayload = {
  update: {
    name: "",
    email: "",
    phone: "",
    password: "",
    is_agent: 1,
    commission: "",
    status: "",
    business_name: "",
    business_phone: "",
    is_vip: 0,
    fixed_deposit_amount: 0,
    deposit_amount: 0,
    deposit_balance: 0,
    credit_amount: 0,
    credit_balance: 0,
    top_up_amount: 0,
    counter: "",
    role_names: "",
  },
  store: {
    name: "",
    email: "",
    phone: "",
    password: "",
    is_agent: 1,
    commission: "",
    status: "",
    business_name: "",
    business_phone: "",
    is_vip: 0,
    fixed_deposit_amount: 0,
    deposit_amount: 0,
    deposit_balance: 0,
    credit_amount: 0,
    credit_balance: 0,
    top_up_amount: 0,
    counter: "",
    role_names: "",
  },
  columnsName: "agentColumns",
  columns: [
    { id: "id", label: "Id", minWidth: 60 },
    { id: "business_name", label: "Business Name", minWidth: 100 },
    { id: "counter", label: "Counter", minWidth: 100 },
    { id: "commission", label: "Commission", minWidth: 100 },
    {
      id: "fixed_deposit_amount",
      label: "Fixed Deposit Amount",
      minWidth: 100,
    },
    {
      id: "deposit_amount",
      label: "Deposit Amount",
      minWidth: 100,
    },
    {
      id: "deposit_balance",
      label: "Deposit Balance",
      minWidth: 100,
    },
    { id: "credit_amount", label: "Credit", minWidth: 100 },
    { id: "credit_balance", label: "Credit Balance", minWidth: 100 },
    { id: "is_vip", label: "Is Vip", minWidth: 150 },
    { id: "name", label: "Name", minWidth: 150 },
    { id: "email", label: "Email", minWidth: 100 },
    { id: "phone", label: "Phone", minWidth: 100 },
    { id: "business_phone", label: "Business Phone", minWidth: 100 },

    { id: "created_by", label: "Created By", minWidth: 100 },
    { id: "updated_by", label: "Updated By", minWidth: 100 },
    { id: "created_at", label: "Created At", minWidth: 100 },
    { id: "updated_at", label: "Updated At", minWidth: 100 },

    { id: "option", label: "Option", minWidth: 100 },
  ],
  paginateParams: {
    page: 1,
    per_page: 10,
    columns:
      "name,business_name,counter,commission,fixed_deposit_amount,deposit_amount,deposit_balance,is_vip,credit_amount,credit_balance,email,phone,business_phone,created_at,updated_at,option",
    search: "",
    order: "id",
    sort: "ASC",
    value: "",
    start_date: "",
    end_date: "",
    is_agent: true,
  },
};
