export const couponPayload = {
  update: {
    code: "",
    type: "percentage",
    value: 0,
    channels: [],
    valid_from: "",
    valid_until: "",
    per_user_limit: 1,
    max_quantity_per_use: null,
    max_total_quantity: null,
    min_order_amount: null,
    is_active: true,
  },
  store: {
    code: "",
    type: "percentage",
    value: 0,
    channels: [],
    valid_from: "",
    valid_until: "",
    per_user_limit: 1,
    max_quantity_per_use: null,
    max_total_quantity: null,
    min_order_amount: null,
    is_active: true,
  },
  columnsName: "couponColumns",
  columns: [
    { id: "id", label: "Id", minWidth: 60 },
    { id: "code", label: "Code", minWidth: 120 },
    { id: "type", label: "Type", minWidth: 100 },
    { id: "value", label: "Value", minWidth: 80 },
    { id: "channels", label: "Channels", minWidth: 200 },
    { id: "valid_from", label: "Valid From", minWidth: 160 },
    { id: "valid_until", label: "Valid Until", minWidth: 160 },
    { id: "per_user_limit", label: "Per User", minWidth: 110 },
    { id: "max_quantity_per_use", label: "Max/Use", minWidth: 110 },
    { id: "max_total_quantity", label: "Max Total Qty", minWidth: 130 },
    { id: "used_count", label: "Used", minWidth: 90 },
    { id: "is_active", label: "Active", minWidth: 90 },
    { id: "created_at", label: "Created At", minWidth: 160 },
    { id: "option", label: "Option", minWidth: 100 },
  ],
  paginateParams: {
    page: 1,
    per_page: 10,
    columns: "code,name,type,value",
    search: "",
    order: "id",
    sort: "DESC",
    filter: "",
    value: "",
    start_date: "",
    end_date: "",
  },
};

